### ISSUE TITLE
Read Serialized Buffers in Place

### ISSUE THREAD

**Issue by victorstewart** [fraillt/bitsery#19] opened 2019-03-17 05:57 UTC
not sure the effort that would be required to implement this, but, given the memory layout of variables and their data in serialized buffers must (?) be deterministic, it is certainly possible to read buffers in place.

right now I use flatbuffers instead of bitsery to serialize/deserialize the information I exchange between my app and server solely because of the ability to read flatbuffers in place-- in my architecture philosophy of minimizing the usage of server resources and time by executing any work on the client possible. so even though the sum total work to serialize/deserialize with bitsery is much less than with flatbuffers, it's still the less optimal choice.

adding this ability would instantly make bitsery the absolutely optimal choice for networking!

**Comment by fraillt** [comment] 2019-03-19 07:59
It's a really interesting idea, that is worth exploring.
In bitsery memory layout of variables in the buffer might not be deterministic, because bitsery allows all sorts of complex flows that might depend on external dynamic context, but this is not an issue to implement this.
Flatbuffers has a concept of `table` that basically stores the pointers to its fields.
Bitsery has a thing called `buffer sessions`, that basically has the inner buffer (defined by a begin and end iterators) within the real buffer. The problem is that currently there is no way to "jump" between sessions, but this is easily implementable.
So the only real problem is to define a convenient API that would allow associating the object with the buffer session in a statically safe manner.
Let's leave this issue open, I'll think about this more and would like to implement it, but maybe you or someone else want to do it faster/better than me ;)

**Comment by fraillt** [comment] 2019-07-09 05:16
Ability to directly manipulate write/read position during serialization/deserialization was added in bitsery 5.0.0. This enables to implement this feature.

**Comment by fraillt** [comment] 2019-11-06 09:16
Closing, because there are too many different ways to implement this. 
The best approach is to write your implementation, that fully satisfies your needs, instead of providing a general solution which is not ideal for anyone.

**Closed by fraillt** 2019-11-06 09:16 UTC
Labels: enhancement, help wanted

**Comment by victorstewart** [comment] 2020-07-18 00:39
Sorry I never got back to you on this topic. I’ve been buried in work for literally years lol.

On implementing this, it seems all we’d need to do is append the offsets of each variable type to the head or tail of the buffer, and then the entire memory layout is deterministic.

This work would also enable updating the buffer in-place. (Extremely valuable for cached buffers).

Then we could leave building interfaces into the buffer to users, which is the real busy work nightmare.

**Comment by fraillt** [comment] 2020-07-19 17:56
Hello,
If I understand correctly, the way you described its quite different the from how bitsery works now...
I was thinking that something similar could be achieved by creating a "wrapper" type, that would store bytes and only deserialize on request. E.g. its public interface could look something like this:
```cpp
class InPlace<T> {
public:
 const T& get_read_only() {
   if state == not_read {
    ... deserialize
  }
  return data.obj
 }
 T& get_mutable() {
   if state == not_read {
    ... deserialize  
  }
 state = modified;
  return data.obj
 }
private:
  union {
    T obj,
    buffer bytes,
  } data;
  int8 state; //one of not_read, read, modified,
}
```

This would allow to have a object like `InPlace<MyComplexType>` that can be serialized/deserialized on the fly.
Not sure how end result would look like and if its useful though...

**Comment by victorstewart** [comment] 2020-07-19 18:46
@fraillt 

So the problem is that, at least for me, the point of reading in-place is to avoid all copies and allocations. This is the reason why at the moment I use a mixture of Bitsery and Flatbuffers throughout my clients and servers, to avoid all those wasted cycles.

When my client serializes a Flatbuffer buffer and sends it to the server, the server can directly read the buffer in-place, and take action. Avoiding allocations and copies entirely. These costs add up when a buffer must be read many times over the course of its lifetime.

This direct access into the buffer, without deserializing into an object, also enables another huge feature which is **write in-place**.

Imagine a situation where I cache a large serialized buffer of a user in Redis. Now the user updates a boolean field. For me to update that field in the buffer, I'd have to deserialize it into an object, change the field value, then reserialize it back into a buffer.

That's a whole lot of work, when If i knew the offset into the buffer of that boolean field value, I could directly write that memory.

**Comment by victorstewart** [comment] 2020-07-19 19:06
This is what I'm talking about. Or maybe you have a much better way in mind to do this. Without static reflection and generative techniques it's always going to be a bit of a mess though.

```
class CustomType {
public:

	int64_t variableA;
	int64_t variableB;
	int64_t variableC;
};

enum class CustomTypeAccess : uint8_t {

	accessA,
	accessB,
	accessC
};

template <typename ... TypesAndValues>
class InPlace {
private:

	uint8_t *buffer;
	size_t bufferSize;

public:

	template <CustomTypeAccess accessor>
	auto genericGet()
	{
		return (GetType<accessor> *)(buffer + OffsetForAccessor<accessor>);
	}

	InPlace(uint8_t *_buffer, size_t _bufferSize) : buffer(_buffer), bufferSize(_bufferSize) {}
};


InPlace<int64_t, CustomTypeAccess::accessA, int64_t, CustomTypeAccess::accessB, int64_t, CustomTypeAccess::accessC>
```

**Comment by fraillt** [comment] 2020-07-20 16:20
Yes, I understand. But I think that in order to make it usable without too much macro or template wizardry it would be best to have an IDL for this...
On the other hand, if you're willing to go that far, then maybe it would make sense to think  of ways bitsery could become friends with flatbuffers? Maybe it would be possible to introduce an extension that would allow to serialize/deserialize flatbuffer object behind the scenes for you? This way you could mix both: flexibility & performance of bitsery, and in-place manipulation of flatbuffers.
Thoughts?

**Comment by victorstewart** [comment] 2020-07-23 02:21
@fraillt 

Do you mean build a new serialization module for Bitsery that serializes the output buffer to the Flatbuffer blueprint? So that I can use the Flatbuffer interface to access it?

That's a neat idea.

If I were to go that far, I'd probably just implement my own custom interface to supercharge the subset of ways I interact with my buffers (which currently amounts to bending Flatbuffers to my will).

I have no pressing need beyond better performance, given I have solutions and code that works very well right now. So I think for now I'll just wait until GCC or Clang have implemented the Reflection TS, and then I'll play around with creating a generic in-place reader for Bitsery.

**Comment by victorstewart** [comment] 2020-07-23 02:35
RE [http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0707r3.pdf](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0707r3.pdf)

**Comment by victorstewart** [comment] 2021-11-18 18:36
had a thought on this. 

we could define a Concept that implements in interface that returns all the static reflection type information as constexpr or consteval (either filling a reflection object or multiple functions). then have people implement it for their types the same way they do serialize functions.

**Comment by victorstewart** [comment] 2023-11-13 18:15
Reflection will be included in C++26, which paves the way for this to be implemented.

**Comment by victorstewart** [comment] 2025-06-21 15:47
https://herbsutter.com/2025/06/21/trip-report-june-2025-iso-c-standards-meeting-sofia-bulgaria/
